import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt, numpy as np
plt.rcParams.update({"font.family":"Liberation Serif","font.size":11})
f=321.943/232.957; avoided=15*0.113*60090
full=avoided/(15*3908*f); ong=avoided/(15*3185*f)
s=np.linspace(0,1,101)
INK="#0b0b0b"; INK2="#52514e"; GRID="#e4e3df"; B="#2a78d6"; O="#eb6834"
fig,ax=plt.subplots(figsize=(6.5,4.2),dpi=300)
ax.axhspan(0,1,color="#f3f2ef",zorder=0)
ax.axhline(1,color=INK2,lw=1,ls=(0,(4,3)),zorder=1)
ax.text(0.02,1.03,"Break-even (ratio = 1.0)",color=INK2,fontsize=9,va="bottom")
ax.text(0.30,0.1,"Program loses money",color=INK2,fontsize=9,style="italic",ha="left")
ax.plot(s,ong*s,color=O,lw=2,ls=(0,(6,2)),zorder=3)
ax.plot(s,full*s,color=B,lw=2,zorder=3)
for r,c in((full,B),(ong,O)):
    ax.plot([0.5,1],[r*.5,r],"o",ms=6,color=c,mec="white",mew=1.5,zorder=4)
    be=1/r; ax.plot([be],[1],"o",ms=6,mfc="white",mec=c,mew=2,zorder=4)
    ax.plot([be,be],[0,1],color=c,lw=0.8,ls=":",zorder=2)
    ax.text(be,0.02,f"{be:.0%}",color=INK,fontsize=9,ha="center",va="bottom",
            bbox=dict(fc="#f3f2ef",ec="none",pad=1))
ax.text(1.02,full,f"Full cost\n{full:.2f}",color=INK,fontsize=9.5,va="center")
ax.text(1.02,ong,f"Ongoing cost only\n{ong:.2f}",color=INK,fontsize=9.5,va="center")
ax.annotate(f"{full*.5:.2f}",(0.5,full*.5),xytext=(8,-10),textcoords="offset points",fontsize=9,color=INK)
ax.annotate(f"{ong*.5:.2f}",(0.5,ong*.5),xytext=(-26,6),textcoords="offset points",fontsize=9,color=INK)
ax.text(0.5,1.62,"Half effect",color=INK2,fontsize=9,ha="center")
ax.axvline(0.5,color=GRID,lw=1,zorder=0.5)
ax.set_xlim(0,1); ax.set_ylim(0,1.7)
ax.set_xticks(np.arange(0,1.01,.25)); ax.set_xticklabels(["0%","25%","50%","75%","100%"])
ax.set_xlabel("Share of the published turnover reduction the hospital achieves",color=INK)
ax.set_ylabel("ROI ratio (avoided turnover cost ÷ program cost)",color=INK)
for sp in("top","right"): ax.spines[sp].set_visible(False)
for sp in("left","bottom"): ax.spines[sp].set_color(INK2)
ax.tick_params(colors=INK2)
ax.grid(axis="y",color=GRID,lw=0.8); ax.set_axisbelow(True)
fig.subplots_adjust(right=0.8)
fig.savefig(__import__("os").path.join(__import__("os").path.dirname(__file__),"figure2_roi_breakeven.png"),bbox_inches="tight",facecolor="white")
print(full,ong,1/full,1/ong)
